config/routes.rb
Rails.application.routes.draw do
  root 'nft_collections#index'

  resources :nft_collections, only: [:index, :show]
  resources :user_wallets, only: [:create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/nft_collection.rb
class NftCollection < ApplicationRecord
  def self.replaced_ipfs_image_url(ipfs_image_link)
    return ipfs_image_link if ipfs_image_link.exclude?('ipfs://')
    "http://ipfs.io/ipfs/#{ipfs_image_link.sub('ipfs://', '')}"
  end
end

app/models/user_wallet.rb
class UserWallet < ApplicationRecord
  validates :address, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nft_collections_controller.rb
class NftCollectionsController < ApplicationController
  before_action :set_nft_collection, only: [:show]

  def index
    @nft_collections = NftCollection.all
  end

  def show
    nft_row_datas = Web3Api::Moralis::Client.nfts_by_contract(
      chain: @nft_collection.chain,
      address: @nft_collection.contract_address,
      limit: 100)
    nft_token_datas = nft_row_datas["result"].map do |data|
      next if data.nil?
      next if data["token_address"].nil?
      next if data["metadata"].nil?
      next if data["minter_address"].nil?
      {
        token_address: data["token_address"],
        token_id: data["token_id"],
        metadata: JSON.parse(data["metadata"]),
        minter_address: data["minter_address"],
      }
    end

    nft_token_datas.compact!
    @nfts = Kaminari.paginate_array(nft_token_datas)
                    .page(params[:page]).per(12)
  end

  private

  def set_nft_collection
    @nft_collection = NftCollection.find(params[:id])
  end
end

app/controllers/user_wallets_controller.rb
class UserWalletsController < ApplicationController
  def create
    message = params["message"]
    address = params["address"]
    signature = params["signature"]


    if Eth::Signature.verify message, signature, address
      @user_wallet = UserWallet.find_by(address: address)
      if @user_wallet.present?
        session[:user_wallet_id] = @user_wallet.id
        render json: { logged_in: session[:user_wallet_id].present? }
        return
      end

      eth_address = Eth::Address.new address
      if eth_address.valid?
        @user_wallet = UserWallet.find_or_create_by(address: address)
        session[:user_wallet_id] = @user_wallet.id
        render json: { connected: session[:user_wallet_id].present? }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nft_collections_helper.rb
module NftCollectionsHelper
end

app/helpers/user_wallets_helper.rb
module UserWalletsHelper
  def current_user_wallet
    @current_user_wallet ||= UserWallet.find_by(id: session[:user_wallet_id])
  end
end

app/views/layouts/_header.html.erb
<nav class="
            flex items-center justify-between
            flex-wrap bg-teal-500 p-6
           "
>
  <div class="
              flex items-center flex-shrink-0
              text-white mr-6
             "
  >
    <span class="font-semibold text-xl tracking-tight">
      Yamori NFT
    </span>
  </div>
  <div
    data-controller="metamask"
    class="items-center w-auto">
    <% if current_user_wallet.nil? %>
      <a
        data-action="click->metamask#signin"
        href="#"
        class="
          inline-block text-sm px-4
          py-2 leading-none border
          rounded text-white border-white
          hover:border-transparent
          hover:text-teal-500
          hover:bg-white
          lg:mt-0"
      >
        ウォレットに接続
      </a>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NftMarketOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main class="container mx-auto px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/nft_collections/index.html.erb
<div class="grid">
  <div
    class="
      h-96 w-full flex
      items-center mt-10
    "
  >
    <div
      class="
        relative bg-cover
        bg-center bg-no-repeat
        w-full h-96
        bg-gradient-to-r from-indigo-500
      "
      style="
        background-image:
          linear-gradient(to bottom, rgba(0, 0, 0, 0),
          rgba(0, 0, 0, 0.6)),
          url('<%= @nft_collections.first.image %>');
      "
    >
      <div
        class="
          absolute bottom-0
          ml-3 mb-3
          text-white font-bold
        "
      >
        <div class="text-3xl">
          <%= @nft_collections.first.name %>
        </div>
        <div class="text-xl">
          <%= @nft_collections.first.creater_name %>
        </div>
      </div>
    </div>
  </div>
  <div
    class="
      pt-10 pb-10 flex
      overflow-x-auto whitespace-nowrap
      gap-4 pr-4
    "
  >
    <% @nft_collections.each do |nft_collection|%>
      <%= link_to nft_collection_path(nft_collection) do %>
        <div
          class="
            relative w-80 h-48 flex-shrink-0
            bg-cover bg-center rounded-lg
          "
          id=<%= "#{nft_collection.contract_address}" %>
          style="background-image:
                  linear-gradient(to bottom, rgba(0, 0, 0, 0),
                  rgba(0, 0, 0, 0.3)),
                  url('<%= nft_collection.image %>');
                "
        >
          <div
            class="absolute top-0 ml-3 mt-3"
            id=<%= "#{ nft_collection.id }" %>
          >
            <%=
              image_tag nft_collection.creater_image,
              class: "h-16 w-16 object-cover rounded-full"
            %>
          </div>
  
          <div
            class="
              absolute bottom-0 ml-3 mb-3
              text-white font-bold
            "
            id="collection-name"
          >
            <%= nft_collection.name %>
          </div>
          <div id=<%= "#{nft_collection.creater_name}"%>></div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/nft_collections/show.html.erb
<p class="pt-5">Created by</p>
<h1 class="font-semibold text-3xl">
  <%= @nft_collection.name %>
</h1>
<div class="flex justify-center">
  <div class="pt-5 pb-20">
    <%= turbo_frame_tag "nfts-page-#{@nfts.current_page}" do %>
      <div
           data-controller="metamask"
           class="
              grid grid-cols-1 items-center
              sm:grid-cols-2 md:grid-cols-3
              lg:grid-cols-4 xl:grid-cols-6
              gap-x-8
           "
      >
        <% @nfts.each do |nft| %>
          <div class="grid pt-5 py-4">
            <div class="shadow-lg rounded-b-md">
              <% if nft.present? && nft[:metadata].present? %>
                <%=
                  image_tag NftCollection.replaced_ipfs_image_url(nft[:metadata]["image"]),
                  class: "w-60 h-60 rounded-lg pb-2"
                %>
              <% end %>
              <div class="grid">
                <div class="my-4 mx-2">
                  <% if nft.present? && nft[:metadata].present? %>
                    <p class="font-semibold"><%= nft[:metadata]["name"].to_s %></p>
                  <% end %>
                  <% if nft.present? && nft[:minter_address].present? %>
                    <p class="font-semibold"><%= nft[:minter_address]&.slice(0..5) %></p>
                  <% end %>
                </div>
                <% if current_user_wallet.nil? %>
                 <button class="bg-teal-500 py-3 mx-2 mb-3 items-center flex justify-center">
                   <p
                     data-action="click->metamask#buyNFT"
                     class="text-white leading-none"
                     id="<%= nft[:token_id] %>"
                   >
                     購入
                   </p>
                 </button>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <%=
        turbo_frame_tag "nfts-page-#{@nfts.next_page}",
        loading: :lazy,
        src: path_to_next_page(@nfts)
      %>
    <% end %>
  </div>
</div>

app/views/user_wallets/create.html.erb
<div>
  <h1 class="font-bold text-4xl">UserWallets#create</h1>
  <p>Find me in app/views/user_wallets/create.html.erb</p>
</div>